development: &dev
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  bot_publish_password: <%= ENV["BOT_PUBLISH_PASSWORD"] %>
  spreadsheet_id: <%= ENV["SPREADSHEET_ID"] %>

  telegram:
    bot:
      token: <%= ENV["BOT_TOKEN"] %>
      username: <%= ENV["BOT_NAME"] %>
      # async: true
      # botan:
      #   token: botan_token
      #   # async: true

test:
  secret_key_base: e19c00c2cde1a2695ba1c98352409788ea66352b90605c3ca6495ba4653cd67866da6d682fb7179d5bc4239deedda1924b5477d60327be5afcd6b3a0bfdab00c

  telegram:
    bot:
      token: test_bot_token
      username: BOT_NAME

production:
  <<: *dev
